Wdog trigger during decompressio for portenta
arduino-libraries/ArduinoIoTCloud pull request #261
Opened 2021-06-10 20:58 UTC by pennam

Needs https://github.com/arduino-libraries/Arduino_Portenta_OTA/pull/10

TODO drop Enable debug output commit

2021-06-11 06:31 UTC, aentinger requested changes

2021-06-11 06:31 UTC, aentinger commented on src/ArduinoIoTCloudTCP.cpp
> +      WiFi.setFeedWatchdogFunc((voidPrtFuncPtr)watchdog_reset);
Bad idea ;)

2021-06-11 12:21 UTC, pennam commented on src/ArduinoIoTCloudTCP.cpp
> +      WiFi.setFeedWatchdogFunc((voidPrtFuncPtr)watchdog_reset);
fixed with https://github.com/arduino-libraries/ArduinoIoTCloud/pull/261/commits/21c15bbdc9b10282b6cab9c347387feace85a444

2021-06-15 04:40 UTC, aentinger approved these changes
LGTM :+1: Thank you @pennam :rocket:

2021-06-15 04:40 UTC, merged