chore: clean examples
arduino-libraries/ArduinoIoTCloud pull request #426
Opened 2024-02-18 00:07 UTC by zfields

- Remove/replace deprecated API calls
- Minimize file inclusions
- Fix whitespace

2024-02-19 14:44 UTC, zfields commented
Rebased to consider latest merge

2024-03-15 08:22 UTC, pennam requested changes
@zfields I get your point, but I would love to keep the include of the example as equal as possible to the examples generated from the cloud editor. We have two differences:
 - In #412 we have moved the `#include "arduino_secrets.h"` from the .ino to the `thingProperties.h` file
 - We kept the `#include <Arduino_ConnectionHandler.h>` in the `arduino_secrets.h` file because we need to know which secrets to include.
 
Moreover the `AIoTC_Config.h` is somehow an internal configuration file and was not really ment to be included in the sketch files.

2024-03-15 08:22 UTC, pennam commented on examples/ArduinoIoTCloud-Schedule/thingProperties.h
> +  ArduinoCloud.addProperty(yearly, Permission::ReadWrite).onUpdate(nullptr);
```suggestion
  ArduinoCloud.addProperty(switchButton, Permission::Write);
  ArduinoCloud.addProperty(oneShot, Permission::ReadWrite);
  ArduinoCloud.addProperty(minute, Permission::ReadWrite);
  ArduinoCloud.addProperty(hourly, Permission::ReadWrite);
  ArduinoCloud.addProperty(daily, Permission::ReadWrite);
  ArduinoCloud.addProperty(weekly, Permission::ReadWrite);
  ArduinoCloud.addProperty(monthly, Permission::ReadWrite);
  ArduinoCloud.addProperty(yearly, Permission::ReadWrite);
```

2024-03-15 08:22 UTC, pennam commented on examples/ArduinoIoTCloud-Schedule/thingProperties.h
> +  ArduinoCloud.addProperty(switchButton, 1, Permission::Write).onUpdate(nullptr);
```suggestion
  ArduinoCloud.addProperty(switchButton, 1, Permission::Write);
```

2024-03-15 12:58 UTC, zfields commented
> Moreover the `AIoTC_Config.h` is somehow an internal configuration file and was not really meant to be included in the sketch files.

It appears the internal configuration is already spilling out into the example. `arduino_secrets.h` is using `#define` variables that originate from `AIoTC_Config.h` (e.g. `BOARD_HAS_WIFI`, `BOARD_HAS_SECRET_KEY`, `BOARD_HAS_GSM`, `BOARD_HAS_NB`, `BOARD_HAS_CATM1_NBIOT`, `BOARD_HAS_LORA`, `BOARD_HAS_ETHERNET`).

I agree that parity between the cloud generated examples and the examples in the library is of the utmost importance. I thought changing it here would also change it there. I will change back the headers to match the cloud.

My only feedback, is that it is currently rather confusing to understand where variables are coming from, and how things are being put together.

2024-03-15 13:36 UTC, zfields commented
@pennam I've implemented your requested changes and rebased on the latest release (0.15.1). :+1:

2024-03-15 13:45 UTC, pennam approved these changes
:+1:

2024-03-30 17:02 UTC, zfields commented
rebased on `master`

2024-04-02 08:46 UTC, merged