Fix time validity check to account for maximum possible timezone offset
arduino-libraries/ArduinoIoTCloud pull request #507
Opened 2024-08-23 15:58 UTC by kytpbs

Fixes #506

2024-08-23 15:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/arduino-libraries/ArduinoIoTCloud?pullRequest=507) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/arduino-libraries/ArduinoIoTCloud?pullRequest=507) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/arduino-libraries/ArduinoIoTCloud?pullRequest=507) it.</sub>

2024-08-30 10:05 UTC, kytpbs commented
@pennam could you review the PR? Would be very appreciated.

2024-09-09 15:17 UTC, pennam requested changes
Hi @kytpbs,
thanks for your contribution and sorry for the delay I was OOF the past two weeks. I've got only one style change request. I suggested you the changes in order to match the comment style of the rest of the file.

Thanks

2024-09-09 15:17 UTC, pennam commented on src/utility/time/TimeService.cpp
> +  return (time > (EPOCH_AT_COMPILE_TIME - (/*UTC+14*/ 14 * 60 * 60)));
```suggestion
  /* EPOCH_AT_COMPILE_TIME is in local time, so we need to subtract the maximum
   * possible timezone offset UTC+14 to make sure we are less then UTC time
   */
  return (time > (EPOCH_AT_COMPILE_TIME - (14 * 60 * 60)));
```

2024-09-09 15:34 UTC, pennam commented
Thanks, tomorrow morning i will give this PR the last spin and then i will merge it.

2024-09-10 08:31 UTC, pennam commented
Hi @kytpbs I've made some tests and found a glitch with this changes:

`EPOCH_AT_COMPILE_TIME` is now considered a valid time and thus it will be stored inside the RTC instead of skipping it and retry to get a valid time.

I'm working to fix this regression and will propose you a couple of commits to be integrated in this PR.

2024-09-11 09:29 UTC, pennam commented
Hi @kytpbs I've prepared this two commits if you want to cherry-pick them and doublecheck your issue is fixed.

https://github.com/pennam/ArduinoIoTCloud/commit/419b39baae50bcfb2ec62002465850ab941c7347
https://github.com/pennam/ArduinoIoTCloud/commit/012b73e65da49298493aa70f64a9f00dcf996ae6

2024-09-11 12:28 UTC, kytpbs commented
at these [lines](https://github.com/pennam/ArduinoIoTCloud/commit/012b73e65da49298493aa70f64a9f00dcf996ae6#diff-6c5ff72bf95a5ae6b9c05d69677ba6f2c95c60e88f67e99dbe1e1ff2ea0849e5L172-L178) 
```cpp
#ifdef HAS_TCP
    utc = getRemoteTime();
#endif
#ifdef HAS_LORA
    /* Just keep incrementing stored RTC value*/
    /* Just keep incrementing stored RTC value starting from EPOCH_AT_COMPILE_TIME */
    utc = getRTC();
#endif
```

shouldn't we first check if we have RTC and use that and return or vice versa, since if `HAS_TCP` and `HAS_LORA` are both defined (for example ESP32), we will first get the remote time, just to overwrite it to `getRTC`? I know this is not part of the commits but it peaked my interest looking at the diffs

2024-09-11 13:22 UTC, pennam commented
Hi @kytpbs thanks for checking! None of the supported boards has both `HAS_TCP` and `HAS_LORA` defined. The sync method is intended as a way to keep in sync the RTC with some other more reliable time source:

If user has defined a custom sync function, this method will be used otherwise if baord `HAS_TCP` we try to get time from NTP of connection handler. Afaik there is no (simple) way to get a timestamp from LoRa network so we rely on the RTC value that at boot time would be configured to `EPOCH_AT_COMPILE_TIME`.

If in the future we will have a board with both TCP and LoRa probably it would be better to rewrite the function like this to avoid overwriting the value:

```
#ifdef HAS_TCP
    utc = getRemoteTime();
#else
    /* Just keep incrementing stored RTC value starting from EPOCH_AT_COMPILE_TIME */
    utc = getRTC();
#endif
```

2024-09-11 13:32 UTC, kytpbs commented
Thanks for the explanation

I will double-check if the issue is fixed tonight if I can since it only occurs after 12 AM

what should I do with your commits/branch
- cherry-pick add them to this branch
- merge that branch into this one
- do nothing since you will just merge your branch which also has my commits instead?

2024-09-12 00:37 UTC, kytpbs commented
Just tested my branch and things worked correctly

2024-09-12 07:03 UTC, pennam commented
@kytpbs Thanks for the test! Please cherry-pick the commits on this branch so we can better keep track of this PR history and related issue.

2024-09-16 08:26 UTC, pennam commented
Superseded by #509

2024-09-16 08:26 UTC, closed without merging